In [ ]:
--1 Show the consultants with names starting with the character “P”.
SELECT ConsultantName
FROM dbo.Consultants
WHERE ConsultantName LIKE 'P%';
--2. Show the consultants that have a last name ending in “ska” and a first name starting with “M”.
SELECT ConsultantName
FROM dbo.Consultants
WHERE dbo.Consultants LIKE 'M% %ska';
--3 Show the consultants whose first name has exactly 5 characters. You can use the LIKE operator or the LEN function.
SELECT ConsultantName
FROM dbo.Consultants
WHERE dbo.Consultants LIKE '%_____';
--4. Show the consultants whose first name has at least 5 characters.
SELECT ConsultantName
FROM dbo.Consultants
WHERE dbo.Consultatns LIKE '%_____%';
--5. Show the products that have a name consisting of at least 2 words.
SELECT *
FROM dbo.Products P
WHERE P.ProductName LIKE '% %';
--6. Show the products that have a name consisting of exactly 2 words.
SELECT ProductName
FROM dbo.Products
WHERE P.ProductName LIKE '% %' AND  P.ProductName NOT LIKE '% % %';
--7. Show the products that contain the letter “D” in lowercase or uppercase.
SELECT ProductName
FROM dbo.Products
WHERE LOWER(ProductName) LIKE '%d%' OR UPPER(ProductName) LIKE '%D%';
--8. Show the names of the products that were never ordered.
SELECT ProductName
FROM dbo.Products P
LEFT JOIN dbo.OrderDetails OD ON P.ProductID = OD.ProductID
WHERE OD.ProductID IS NULL
--9. Show the ID and the sum of the amount for each order.
SELECT OD.OrderID, SUM(OD.Quantity) as quantity_sum
FROM dbo.OrderDetails OD
GROUP BY OrderID
--10. Show the ID of each product and the number of orders in which it is included.
SELECT ProductID, COUNT (DISTINCT OrderID) as num_orders
FROM dbo.OrderDetails
GROUP BY ProductID
--11 . Show all product details for products that were ordered at least twice (i.e., that appear in 2 different orders)
SELECT P. *, COUNT(od.OrderID) AS order_count
FROM Products P
JOIN OrderDetails OD ON P.ProductID = OD.ProductID
GROUP BY P.ProductID
HAVING COUNT(OD.OrderID) >= 2;
--12. Show the total profit of each consultant separately.
SELECT O.ConsultantID, SUM(P.ProductPrice * OD.Quantity) AS total_profit
FROM Orders O 
JOIN OrderDetails OD ON O.OrderID = OD.OrderID
JOIN Products P ON OD.ProductID = P.ProductID
GROUP BY O.ConsultatID
--13 Show the names of the products that are not part of the Perfume category but have higher
--prices than at least one perfume (a product that is in the Perfume category)
SELECT ProductName
FROM dbo.Products P 
JOIN dbo.Categories C ON P.CategoryID > C.CategoryID
--14. Calculate the average profit of all consultants (average of the total profit per consultant).
SELECT AVG(OD.Quantity * P.ProductPrice)
FROM dbo.Consultants C
JOIN Orders O ON C.COnsultantID = O.ConsultantID 
JOIN OrderDetails OD ON O.OrderID = OD.OrderID
JOIN Products P ON OD.ProductID = P.ProductID
GROUP BY C.ConsultantID 
--15 Calculate the average sum of all orders
SELECT AVG(sumtotal) as average_sum
FROM (
     SELECT SUM(OD.Quantity * P.ProductPrice) as sumtotal
     FROM OrderDetails OD
     JOIN Products P ON OD.ProductID = P.ProductID
     GROUP BY OD.OrderID
     )
     AS OrderSubtotals;
--16. Calculate the average number of products per order.
SELECT AVG(product_count) as average_products_per_order
FROM (
     SELECT OrderID, COUNT(OD.Quantity) AS product_count
     FROM OrderDetails OD
     GROUP BY OrderID
     ) AS OrderProductsCount;
--17Find the most expensive product, the number of orders it appears in, and the number of 
--consultants that have sold it. Then display the names of the consultants that have ever sold it